NSTRUCTIONS
 * =========================
 *  * 
 *   *  Write two functions between the comments
 *    *  indicated below.
 *     * 
 *        The first function will take two referenced
 *         *  pointers to a Node (this is the head and tail
     *          * of the list respectively),
 *           * an array of numbers and the size of the array. 
 *            * It will then build a linked list from these numbers
 *             * using any method (backward, forward or sorted).
 *              * NOTE:  if your method of building the list doesn't
 *               * need the tail pointer you can ignore it in your
 *                * functions but the both functions still need to
 *                 * take it in as a parameter.
 *                  * 
 *                   *    The second function will take the head and tail of
 *                    * the list.  It will find the first even number in the
 *                    list
 *                     *  and remove the node from the list. Remember to
 *                      *  delete the node after removing it from the list.
 *                       *  If there are no even numbers in the list the
 *                       function
 *                        *  does nothing to the list.
 *                         * 
 *                          * PLEASE SEE MAIN FUNCTION BELOW FOR NAMES OF 
 *                           * FUNCTIONS AND WHAT ORDER THE PARAMETERS ARE IN
 *                            * REMEMBER YOUR CODE NEEDS TO MATCH THESE CALLS.
 *                             * 
 *                              * NOTES
 *                               * ===================================
 *                                * You can change this file all you want
 *                                during
 *                                 * the exam but keep in mind that I will ONLY
 *                                 BE
 *                                  * USING YOUR FUNCTIONS by copying them to
 *                                  another
 *                                   * main.cpp file.
 *                                    * 
 *                                     * Do not code to the given data. I will
 *                                     be using 
 *                                      * different values in my grading source
 *                                      code file.
 *                                       * 
 *                                        * Do not use global
 *                                        variables/constants
 *                                         * or goto's in your code. head and
 *                                         tail pointers
 *                                          * will be provided inside main
 *                                          function
 *                                           * and passed in as parameters to
 *                                           your functions.
 *                                            * 
 *                                             *  You can make more than two
 *                                             functions
 *                                              *  but keep all functions
 *                                              between the
 *                                               *  given comment lines below.
 *                                                * 
 *                                                 * Do not remove the comment
 *                                                 lines as my
 *                                                  * grading script will not
 *                                                  be able to 
 *                                                   * copy your functions over
 *                                                   to my
 *                                                    * grading source file.
 *                                                     * 
 *                                                      * Don't ask the user
 *                                                      for information.  The
 *                                                      main
 *                                                       * function will get
 *                                                       all information needed
 *                                                       and pass it
 *                                                        * into your function.
 *                                                        See main function for
 *                                                         * how your function
 *                                                         will be called.
 *                                                          * 
 *                                                           *
 *                                                            * two example
 *                                                            runs are below:
 *                                                            BEFORE
 *                                                            -----------
 *                                                            1
 *                                                            6
 *                                                            2
 *                                                            8
 *                                                            9
 *                                                            ----------------
 *                                                            AFTER
 *                                                            -----------
 *                                                            1
 *                                                            2
 *                                                            8
 *                                                            9
 *                                                            ----------------
 *
 *
 *                                                            BEFORE
 *                                                            -----------
 *                                                            11
 *                                                            1
 *                                                            7
 *                                                            3
 *                                                            5
 *                                                            9
 *                                                            ----------------
 *                                                            AFTER
 *                                                            -----------
 *                                                            11
 *                                                            1
 *                                                            7
 *                                                            3
 *                                                            5
 *                                                            9
 *                                                            ----------------
 *
 *
 *                                                             */
#include <iostream>
#include <cstring>

 using namespace std;

 struct Node {
       int data;
           Node *next;
 };

// PLEASE PUT YOUR FUNCTION BELOW THIS LINE.
// // DO NOT REMOVE THE COMMENT LINE ABOVE
//
// void buildList(Node* &first, Node* &last, int numbers[], int arraySize)
// {
//     for (int i = 0; i < arraySize; i++)
//         {
//                 Node *newNode;
//                         newNode = new Node;
//                                 newNode->data = numbers[i];
//                                         newNode->next = NULL;
//
//                                                 if(first == NULL)
//                                                         {
//                                                                     first
//                                                                     = newNode;
//                                                                                 last
//                                                                                 = newNode;
//                                                                                         }
//                                                                                                 else
//                                                                                                         {
//                                                                                                                     last->next
//                                                                                                                     = newNode;
//                                                                                                                                 last
//                                                                                                                                 = newNode;
//                                                                                                                                         }
//                                                                                                                                             }
//                                                                                                                                             }
//
//                                                                                                                                             void
//                                                                                                                                             deleteFirstEven(Node*
//                                                                                                                                             &head,
//                                                                                                                                             Node*
//                                                                                                                                             &tail)
//                                                                                                                                             {
//                                                                                                                                                 Node
//                                                                                                                                                 *current;
//                                                                                                                                                     current
//                                                                                                                                                     = new
//                                                                                                                                                     Node;
//                                                                                                                                                         current
//                                                                                                                                                         = head;
//                                                                                                                                                             
//                                                                                                                                                                 Node
//                                                                                                                                                                 *beforeCurrent;
//                                                                                                                                                                     beforeCurrent
//                                                                                                                                                                     = new
//                                                                                                                                                                     Node;
//                                                                                                                                                                         beforeCurrent
//                                                                                                                                                                         = head;
//                                                                                                                                                                             bool
//                                                                                                                                                                             evenFound
//                                                                                                                                                                             = false;
//                                                                                                                                                                                 
//                                                                                                                                                                                     if
//                                                                                                                                                                                     (head
//                                                                                                                                                                                     ==
//                                                                                                                                                                                     NULL)
//                                                                                                                                                                                         {
//                                                                                                                                                                                                 cout
//                                                                                                                                                                                                 <<
//                                                                                                                                                                                                 "WHAT
//                                                                                                                                                                                                 ARE
//                                                                                                                                                                                                 YOU
//                                                                                                                                                                                                 DOING
//                                                                                                                                                                                                 DAVE?
//                                                                                                                                                                                                 I CANNOT
//                                                                                                                                                                                                 DELETE
//                                                                                                                                                                                                 FROM
//                                                                                                                                                                                                 AN
//                                                                                                                                                                                                 EMPTY
//                                                                                                                                                                                                 LIST,
//                                                                                                                                                                                                 DAVE."
//                                                                                                                                                                                                 <<
//                                                                                                                                                                                                 endl;
//                                                                                                                                                                                                         //return
//                                                                                                                                                                                                         head;
//                                                                                                                                                                                                             }
//                                                                                                                                                                                                                 else
//                                                                                                                                                                                                                     {
//                                                                                                                                                                                                                             if
//                                                                                                                                                                                                                             (head->data
//                                                                                                                                                                                                                             % 2 ==
//                                                                                                                                                                                                                             0)
//                                                                                                                                                                                                                                     {
//                                                                                                                                                                                                                                                 cout
//                                                                                                                                                                                                                                                 <<
//                                                                                                                                                                                                                                                 "SUCCESS!"
//                                                                                                                                                                                                                                                 <<
//                                                                                                                                                                                                                                                 endl;
//                                                                                                                                                                                                                                                             head
//                                                                                                                                                                                                                                                             = head->next;
//                                                                                                                                                                                                                                                                         delete
//                                                                                                                                                                                                                                                                         current;
//                                                                                                                                                                                                                                                                                     evenFound
//                                                                                                                                                                                                                                                                                     = true;
//                                                                                                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                                                                                                                     while
//                                                                                                                                                                                                                                                                                                     (evenFound
//                                                                                                                                                                                                                                                                                                     ==
//                                                                                                                                                                                                                                                                                                     false
//                                                                                                                                                                                                                                                                                                     &&
//                                                                                                                                                                                                                                                                                                     current->next
//                                                                                                                                                                                                                                                                                                     !=
//                                                                                                                                                                                                                                                                                                     NULL)
//                                                                                                                                                                                                                                                                                                             {
//                                                                                                                                                                                                                                                                                                                         beforeCurrent
//                                                                                                                                                                                                                                                                                                                         = current;
//                                                                                                                                                                                                                                                                                                                                     current
//                                                                                                                                                                                                                                                                                                                                     = current->next;
//
//                                                                                                                                                                                                                                                                                                                                                 if
//                                                                                                                                                                                                                                                                                                                                                 (current->data
//                                                                                                                                                                                                                                                                                                                                                 % 2 ==
//                                                                                                                                                                                                                                                                                                                                                 0)
//                                                                                                                                                                                                                                                                                                                                                             {
//                                                                                                                                                                                                                                                                                                                                                                             evenFound
//                                                                                                                                                                                                                                                                                                                                                                             = true;
//                                                                                                                                                                                                                                                                                                                                                                                             beforeCurrent->next
//                                                                                                                                                                                                                                                                                                                                                                                             = current->next;
//                                                                                                                                                                                                                                                                                                                                                                                                             delete
//                                                                                                                                                                                                                                                                                                                                                                                                             current;
//                                                                                                                                                                                                                                                                                                                                                                                                                         }
//                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                                                                                     END
//                                                                                                                                                                                                                                                                                                                                                                                                                                     OF
//                                                                                                                                                                                                                                                                                                                                                                                                                                     FUNCTION
//                                                                                                                                                                                                                                                                                                                                                                                                                                     - DO
//                                                                                                                                                                                                                                                                                                                                                                                                                                     NOT
//                                                                                                                                                                                                                                                                                                                                                                                                                                     REMOVE
//                                                                                                                                                                                                                                                                                                                                                                                                                                     THIS
//                                                                                                                                                                                                                                                                                                                                                                                                                                     COMMENT
//                                                                                                                                                                                                                                                                                                                                                                                                                                     LINE.
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                     void
//                                                                                                                                                                                                                                                                                                                                                                                                                                     printList(Node*
//                                                                                                                                                                                                                                                                                                                                                                                                                                     head)
//                                                                                                                                                                                                                                                                                                                                                                                                                                     {
//                                                                                                                                                                                                                                                                                                                                                                                                                                        cout
//                                                                                                                                                                                                                                                                                                                                                                                                                                        <<
//                                                                                                                                                                                                                                                                                                                                                                                                                                        "-----------"
//                                                                                                                                                                                                                                                                                                                                                                                                                                        <<
//                                                                                                                                                                                                                                                                                                                                                                                                                                        endl;
//                                                                                                                                                                                                                                                                                                                                                                                                                                           Node*
//                                                                                                                                                                                                                                                                                                                                                                                                                                           current
//                                                                                                                                                                                                                                                                                                                                                                                                                                           = head;
//                                                                                                                                                                                                                                                                                                                                                                                                                                              while(current) 
//                                                                                                                                                                                                                                                                                                                                                                                                                                                 {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                       cout
//                                                                                                                                                                                                                                                                                                                                                                                                                                                       <<
//                                                                                                                                                                                                                                                                                                                                                                                                                                                       current->data
//                                                                                                                                                                                                                                                                                                                                                                                                                                                       <<
//                                                                                                                                                                                                                                                                                                                                                                                                                                                       endl;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                             current
//                                                                                                                                                                                                                                                                                                                                                                                                                                                             = current->next;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                   cout
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <<
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "----------------"
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <<
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                   endl;  
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                   int
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                   main()
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                   {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Node
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                       *head
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                       = NULL;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Node
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                           *tail
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                           = NULL;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                               int
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                               array[200]
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                               = {1,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                               3,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                               4};
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                count
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                = 4;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        how
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        the
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        first
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            will
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            be
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            called
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                buildList(head,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tail,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                array,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                count);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cout
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <<
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "BEFORE"
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <<
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        endl;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printList(head); 
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    this
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    how
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    the
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    second
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    will
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        be
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        called.
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          deleteFirstEven(head,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tail);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cout
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <<
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "AFTER"
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <<
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                endl;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printList(head); 
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            0;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
